### PR TITLE
Updates for Google Accounts

### PR DESCRIPTION
**Pull request by twang817**
Fixes for Google Apps users.

### CODE REVIEW

**Comment by dblapps** [comment]
Anybody having luck with these changes?  I just tried installing the updated version, and it didn't seem to change anything.

**Comment by twang817** [comment]
You tried the latest gmail-manager-ng?

nedwidek hasn't pulled the changes in yet.  You'll need to extract the xpi and make the changes in this pull request manually.

**Comment by dblapps** [comment]
Yes, that's what I did (I used your forked version).  Didn't seem to help.

**Comment by jfeise** [comment]
It is not quite clear which problems these changes address.
I rebuilt the xpi with the changes, and I don't see any obvious behavior change.

**Comment by twang817** [comment]
I think I see what went wrong.  I patched 0.6.5.2 (locally) on my desktop; then rebased the changes into master.  I do believe current master is broken.

I'll make a 0.6.5.2.1 hotfix and rebuild the xpi.

**Comment by dblapps** [comment]
My assumption was that the changes were supposed to fix the problem where gmail logins were failing.  That seemed to be the only problem being reported recently ...

**Comment by twang817** [comment]
Yes, that is what my fix is.

The problem is the original author's master contains yet-to-be-released code that is broken.

**Comment by twang817** [comment]
nedwidek: Please decline this pull request.

**Comment by twang817** [comment]
All, I've rebased against 0.6.5.2 (which is what was on addons.mozilla.com) and released under 0.6.5.2.1.  You can find the xpi here:

https://github.com/twang817/firefox-gmail-manager-ng/raw/0.6.5.2.1/dist/gmail_manager_ng-0.6.5.2.1.xpi

**Comment by dblapps** [comment]
That did the trick!  It's working now.  Thanks!

**Comment by twang817** [comment]
Your welcome. :)

**Comment by jfeise** [comment]
Working for me as well. Thanks!

**Pull request closed without merging**
